on:
  push:
    branches:
      - master
  pull_request:
jobs:
  build:
    name: Build project
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - name: Validate gradle wrapper checksum
        uses: gradle/actions/wrapper-validation@0bdd871935719febd78681f197cd39af5b6e16a6 # v4.2.2

      - name: Set up JDK 21
        uses: actions/setup-java@7a6d8a8234af8eb26422e24e3006232cccaa061b # v4.6.0
        with:
          distribution: 'temurin'
          java-version: 21
          cache: gradle

      - name: Build and test
        # Debug build only since release builds require a signing key
        run: ./gradlew --no-daemon build zipDebug -x assembleRelease
